version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/edge/traffic"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/cloud/time_serie_ARIMA"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "maven"
    directory: "/cloud/anbao"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/cloud/videoIO"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
